### ISSUE TITLE
Add AbortConditions to Adjustments

### ISSUE THREAD

**Issue by otto-von-bivouac** [deltaray-io/mesosim-tracker#60]
Request by Teresa W:

```
I'd like to use the adjust single leg feature (to get my overall position back closer to delta neutral), but I want to prevent an over-adjustment beyond half of the current position delta. For example, I've noticed in manual backtesting that if I have a +10 pos_delta, sometimes the next closest available strike would create a -5 Delta, which causes an over-adjustment.
```

One potential solution to this request would be to add AbortConditions (similar to the one in AddLegsAdjustment) to MoveLegAdjustment.

**Comment by tibkiss** [comment]
This issue would be also a good place to fix the AdjustmentCnt always updated problem Ron has discovered:
Even if the Adjustment was not executed, the AdjustmentCnt is increased.

**Comment by tibkiss** [comment]
This was delivered via v2.9.x
